from brian.stdunits import *
from brian.units import *

F = 1
N_SUBPOP = 6
INTERCO_RATE = .2
INTERCO_STRENGTH= 0.4

PARAMETERS = {
'Common':
    {'simu_dt'    : 0.05*msecond,
     'simu_length' : 3000*msecond,
     'resample_dt': 0.5*msecond,
     'N_subpop'    : N_SUBPOP,
     'N_mitral'    : N_SUBPOP*100*F,
     'inter_conn_rate': {0: {0: 1.0,
                          1: INTERCO_RATE,
                          2: INTERCO_RATE,
                          3: INTERCO_RATE,
                          4: INTERCO_RATE,
                          5: INTERCO_RATE,
                          6: INTERCO_RATE,
                          7: INTERCO_RATE,
                          8: INTERCO_RATE,
                          9: INTERCO_RATE,
                          10: INTERCO_RATE,
                          11: INTERCO_RATE,
                          12: INTERCO_RATE,
                          13: INTERCO_RATE,
                          14: INTERCO_RATE,
                          15: INTERCO_RATE,
                          16: INTERCO_RATE,
                          17: INTERCO_RATE,
                          18: INTERCO_RATE,
                          19: INTERCO_RATE,
                          20: INTERCO_RATE},
                         1: {0: INTERCO_RATE,
                          1: 1.0,
                          2: INTERCO_RATE,
                          3: INTERCO_RATE,
                          4: INTERCO_RATE,
                          5: INTERCO_RATE,
                          6: INTERCO_RATE,
                          7: INTERCO_RATE,
                          8: INTERCO_RATE,
                          9: INTERCO_RATE,
                          10: INTERCO_RATE,
                          11: INTERCO_RATE,
                          12: INTERCO_RATE,
                          13: INTERCO_RATE,
                          14: INTERCO_RATE,
                          15: INTERCO_RATE,
                          16: INTERCO_RATE,
                          17: INTERCO_RATE,
                          18: INTERCO_RATE,
                          19: INTERCO_RATE,
                          20: INTERCO_RATE},
                         2: {0: INTERCO_RATE,
                          1: INTERCO_RATE,
                          2: 1.0,
                          3: INTERCO_RATE,
                          4: INTERCO_RATE,
                          5: INTERCO_RATE,
                          6: INTERCO_RATE,
                          7: INTERCO_RATE,
                          8: INTERCO_RATE,
                          9: INTERCO_RATE,
                          10: INTERCO_RATE,
                          11: INTERCO_RATE,
                          12: INTERCO_RATE,
                          13: INTERCO_RATE,
                          14: INTERCO_RATE,
                          15: INTERCO_RATE,
                          16: INTERCO_RATE,
                          17: INTERCO_RATE,
                          18: INTERCO_RATE,
                          19: INTERCO_RATE,
                          20: INTERCO_RATE},
                         3: {0: INTERCO_RATE,
                          1: INTERCO_RATE,
                          2: INTERCO_RATE,
                          3: 1.0,
                          4: INTERCO_RATE,
                          5: INTERCO_RATE,
                          6: INTERCO_RATE,
                          7: INTERCO_RATE,
                          8: INTERCO_RATE,
                          9: INTERCO_RATE,
                          10: INTERCO_RATE,
                          11: INTERCO_RATE,
                          12: INTERCO_RATE,
                          13: INTERCO_RATE,
                          14: INTERCO_RATE,
                          15: INTERCO_RATE,
                          16: INTERCO_RATE,
                          17: INTERCO_RATE,
                          18: INTERCO_RATE,
                          19: INTERCO_RATE,
                          20: INTERCO_RATE},
                         4: {0: INTERCO_RATE,
                          1: INTERCO_RATE,
                          2: INTERCO_RATE,
                          3: INTERCO_RATE,
                          4: 1.0,
                          5: INTERCO_RATE,
                          6: INTERCO_RATE,
                          7: INTERCO_RATE,
                          8: INTERCO_RATE,
                          9: INTERCO_RATE,
                          10: INTERCO_RATE,
                          11: INTERCO_RATE,
                          12: INTERCO_RATE,
                          13: INTERCO_RATE,
                          14: INTERCO_RATE,
                          15: INTERCO_RATE,
                          16: INTERCO_RATE,
                          17: INTERCO_RATE,
                          18: INTERCO_RATE,
                          19: INTERCO_RATE,
                          20: INTERCO_RATE},
                         5: {0: INTERCO_RATE,
                          1: INTERCO_RATE,
                          2: INTERCO_RATE,
                          3: INTERCO_RATE,
                          4: INTERCO_RATE,
                          5: 1.0,
                          6: INTERCO_RATE,
                          7: INTERCO_RATE,
                          8: INTERCO_RATE,
                          9: INTERCO_RATE,
                          10: INTERCO_RATE,
                          11: INTERCO_RATE,
                          12: INTERCO_RATE,
                          13: INTERCO_RATE,
                          14: INTERCO_RATE,
                          15: INTERCO_RATE,
                          16: INTERCO_RATE,
                          17: INTERCO_RATE,
                          18: INTERCO_RATE,
                          19: INTERCO_RATE,
                          20: INTERCO_RATE},
                         6: {0: INTERCO_RATE,
                          1: INTERCO_RATE,
                          2: INTERCO_RATE,
                          3: INTERCO_RATE,
                          4: INTERCO_RATE,
                          5: INTERCO_RATE,
                          6: 1.0,
                          7: INTERCO_RATE,
                          8: INTERCO_RATE,
                          9: INTERCO_RATE,
                          10: INTERCO_RATE,
                          11: INTERCO_RATE,
                          12: INTERCO_RATE,
                          13: INTERCO_RATE,
                          14: INTERCO_RATE,
                          15: INTERCO_RATE,
                          16: INTERCO_RATE,
                          17: INTERCO_RATE,
                          18: INTERCO_RATE,
                          19: INTERCO_RATE,
                          20: INTERCO_RATE},
                         7: {0: INTERCO_RATE,
                          1: INTERCO_RATE,
                          2: INTERCO_RATE,
                          3: INTERCO_RATE,
                          4: INTERCO_RATE,
                          5: INTERCO_RATE,
                          6: INTERCO_RATE,
                          7: 1.0,
                          8: INTERCO_RATE,
                          9: INTERCO_RATE,
                          10: INTERCO_RATE,
                          11: INTERCO_RATE,
                          12: INTERCO_RATE,
                          13: INTERCO_RATE,
                          14: INTERCO_RATE,
                          15: INTERCO_RATE,
                          16: INTERCO_RATE,
                          17: INTERCO_RATE,
                          18: INTERCO_RATE,
                          19: INTERCO_RATE,
                          20: INTERCO_RATE},
                         8: {0: INTERCO_RATE,
                          1: INTERCO_RATE,
                          2: INTERCO_RATE,
                          3: INTERCO_RATE,
                          4: INTERCO_RATE,
                          5: INTERCO_RATE,
                          6: INTERCO_RATE,
                          7: INTERCO_RATE,
                          8: 1.0,
                          9: INTERCO_RATE,
                          10: INTERCO_RATE,
                          11: INTERCO_RATE,
                          12: INTERCO_RATE,
                          13: INTERCO_RATE,
                          14: INTERCO_RATE,
                          15: INTERCO_RATE,
                          16: INTERCO_RATE,
                          17: INTERCO_RATE,
                          18: INTERCO_RATE,
                          19: INTERCO_RATE,
                          20: INTERCO_RATE},
                         9: {0: INTERCO_RATE,
                          1: INTERCO_RATE,
                          2: INTERCO_RATE,
                          3: INTERCO_RATE,
                          4: INTERCO_RATE,
                          5: INTERCO_RATE,
                          6: INTERCO_RATE,
                          7: INTERCO_RATE,
                          8: INTERCO_RATE,
                          9: 1.0,
                          10: INTERCO_RATE,
                          11: INTERCO_RATE,
                          12: INTERCO_RATE,
                          13: INTERCO_RATE,
                          14: INTERCO_RATE,
                          15: INTERCO_RATE,
                          16: INTERCO_RATE,
                          17: INTERCO_RATE,
                          18: INTERCO_RATE,
                          19: INTERCO_RATE,
                          20: INTERCO_RATE},
                         10: {0: INTERCO_RATE,
                          1: INTERCO_RATE,
                          2: INTERCO_RATE,
                          3: INTERCO_RATE,
                          4: INTERCO_RATE,
                          5: INTERCO_RATE,
                          6: INTERCO_RATE,
                          7: INTERCO_RATE,
                          8: INTERCO_RATE,
                          9: INTERCO_RATE,
                          10: 1.0,
                          11: INTERCO_RATE,
                          12: INTERCO_RATE,
                          13: INTERCO_RATE,
                          14: INTERCO_RATE,
                          15: INTERCO_RATE,
                          16: INTERCO_RATE,
                          17: INTERCO_RATE,
                          18: INTERCO_RATE,
                          19: INTERCO_RATE,
                          20: INTERCO_RATE},
                         11: {0: INTERCO_RATE,
                          1: INTERCO_RATE,
                          2: INTERCO_RATE,
                          3: INTERCO_RATE,
                          4: INTERCO_RATE,
                          5: INTERCO_RATE,
                          6: INTERCO_RATE,
                          7: INTERCO_RATE,
                          8: INTERCO_RATE,
                          9: INTERCO_RATE,
                          10: INTERCO_RATE,
                          11: 1.0,
                          12: INTERCO_RATE,
                          13: INTERCO_RATE,
                          14: INTERCO_RATE,
                          15: INTERCO_RATE,
                          16: INTERCO_RATE,
                          17: INTERCO_RATE,
                          18: INTERCO_RATE,
                          19: INTERCO_RATE,
                          20: INTERCO_RATE},
                         12: {0: INTERCO_RATE,
                          1: INTERCO_RATE,
                          2: INTERCO_RATE,
                          3: INTERCO_RATE,
                          4: INTERCO_RATE,
                          5: INTERCO_RATE,
                          6: INTERCO_RATE,
                          7: INTERCO_RATE,
                          8: INTERCO_RATE,
                          9: INTERCO_RATE,
                          10: INTERCO_RATE,
                          11: INTERCO_RATE,
                          12: 1.0,
                          13: INTERCO_RATE,
                          14: INTERCO_RATE,
                          15: INTERCO_RATE,
                          16: INTERCO_RATE,
                          17: INTERCO_RATE,
                          18: INTERCO_RATE,
                          19: INTERCO_RATE,
                          20: INTERCO_RATE},
                         13: {0: INTERCO_RATE,
                          1: INTERCO_RATE,
                          2: INTERCO_RATE,
                          3: INTERCO_RATE,
                          4: INTERCO_RATE,
                          5: INTERCO_RATE,
                          6: INTERCO_RATE,
                          7: INTERCO_RATE,
                          8: INTERCO_RATE,
                          9: INTERCO_RATE,
                          10: INTERCO_RATE,
                          11: INTERCO_RATE,
                          12: INTERCO_RATE,
                          13: 1.0,
                          14: INTERCO_RATE,
                          15: INTERCO_RATE,
                          16: INTERCO_RATE,
                          17: INTERCO_RATE,
                          18: INTERCO_RATE,
                          19: INTERCO_RATE,
                          20: INTERCO_RATE},
                         14: {0: INTERCO_RATE,
                          1: INTERCO_RATE,
                          2: INTERCO_RATE,
                          3: INTERCO_RATE,
                          4: INTERCO_RATE,
                          5: INTERCO_RATE,
                          6: INTERCO_RATE,
                          7: INTERCO_RATE,
                          8: INTERCO_RATE,
                          9: INTERCO_RATE,
                          10: INTERCO_RATE,
                          11: INTERCO_RATE,
                          12: INTERCO_RATE,
                          13: INTERCO_RATE,
                          14: 1.0,
                          15: INTERCO_RATE,
                          16: INTERCO_RATE,
                          17: INTERCO_RATE,
                          18: INTERCO_RATE,
                          19: INTERCO_RATE,
                          20: INTERCO_RATE},
                         15: {0: INTERCO_RATE,
                          1: INTERCO_RATE,
                          2: INTERCO_RATE,
                          3: INTERCO_RATE,
                          4: INTERCO_RATE,
                          5: INTERCO_RATE,
                          6: INTERCO_RATE,
                          7: INTERCO_RATE,
                          8: INTERCO_RATE,
                          9: INTERCO_RATE,
                          10: INTERCO_RATE,
                          11: INTERCO_RATE,
                          12: INTERCO_RATE,
                          13: INTERCO_RATE,
                          14: INTERCO_RATE,
                          15: 1.0,
                          16: INTERCO_RATE,
                          17: INTERCO_RATE,
                          18: INTERCO_RATE,
                          19: INTERCO_RATE,
                          20: INTERCO_RATE},
                         16: {0: INTERCO_RATE,
                          1: INTERCO_RATE,
                          2: INTERCO_RATE,
                          3: INTERCO_RATE,
                          4: INTERCO_RATE,
                          5: INTERCO_RATE,
                          6: INTERCO_RATE,
                          7: INTERCO_RATE,
                          8: INTERCO_RATE,
                          9: INTERCO_RATE,
                          10: INTERCO_RATE,
                          11: INTERCO_RATE,
                          12: INTERCO_RATE,
                          13: INTERCO_RATE,
                          14: INTERCO_RATE,
                          15: INTERCO_RATE,
                          16: 1.0,
                          17: INTERCO_RATE,
                          18: INTERCO_RATE,
                          19: INTERCO_RATE,
                          20: INTERCO_RATE},
                         17: {0: INTERCO_RATE,
                          1: INTERCO_RATE,
                          2: INTERCO_RATE,
                          3: INTERCO_RATE,
                          4: INTERCO_RATE,
                          5: INTERCO_RATE,
                          6: INTERCO_RATE,
                          7: INTERCO_RATE,
                          8: INTERCO_RATE,
                          9: INTERCO_RATE,
                          10: INTERCO_RATE,
                          11: INTERCO_RATE,
                          12: INTERCO_RATE,
                          13: INTERCO_RATE,
                          14: INTERCO_RATE,
                          15: INTERCO_RATE,
                          16: INTERCO_RATE,
                          17: 1.0,
                          18: INTERCO_RATE,
                          19: INTERCO_RATE,
                          20: INTERCO_RATE},
                         18: {0: INTERCO_RATE,
                          1: INTERCO_RATE,
                          2: INTERCO_RATE,
                          3: INTERCO_RATE,
                          4: INTERCO_RATE,
                          5: INTERCO_RATE,
                          6: INTERCO_RATE,
                          7: INTERCO_RATE,
                          8: INTERCO_RATE,
                          9: INTERCO_RATE,
                          10: INTERCO_RATE,
                          11: INTERCO_RATE,
                          12: INTERCO_RATE,
                          13: INTERCO_RATE,
                          14: INTERCO_RATE,
                          15: INTERCO_RATE,
                          16: INTERCO_RATE,
                          17: INTERCO_RATE,
                          18: 1.0,
                          19: INTERCO_RATE,
                          20: INTERCO_RATE},
                         19: {0: INTERCO_RATE,
                          1: INTERCO_RATE,
                          2: INTERCO_RATE,
                          3: INTERCO_RATE,
                          4: INTERCO_RATE,
                          5: INTERCO_RATE,
                          6: INTERCO_RATE,
                          7: INTERCO_RATE,
                          8: INTERCO_RATE,
                          9: INTERCO_RATE,
                          10: INTERCO_RATE,
                          11: INTERCO_RATE,
                          12: INTERCO_RATE,
                          13: INTERCO_RATE,
                          14: INTERCO_RATE,
                          15: INTERCO_RATE,
                          16: INTERCO_RATE,
                          17: INTERCO_RATE,
                          18: INTERCO_RATE,
                          19: 1.0,
                          20: INTERCO_RATE},
                         20: {0: INTERCO_RATE,
                          1: INTERCO_RATE,
                          2: INTERCO_RATE,
                          3: INTERCO_RATE,
                          4: INTERCO_RATE,
                          5: INTERCO_RATE,
                          6: INTERCO_RATE,
                          7: INTERCO_RATE,
                          8: INTERCO_RATE,
                          9: INTERCO_RATE,
                          10: INTERCO_RATE,
                          11: INTERCO_RATE,
                          12: INTERCO_RATE,
                          13: INTERCO_RATE,
                          14: INTERCO_RATE,
                          15: INTERCO_RATE,
                          16: INTERCO_RATE,
                          17: INTERCO_RATE,
                          18: INTERCO_RATE,
                          19: INTERCO_RATE,
                          20: 1.0}},
     'inter_conn_strength': {0: {0: INTERCO_STRENGTH,
                              1: INTERCO_STRENGTH,
                              2: INTERCO_STRENGTH,
                              3: INTERCO_STRENGTH,
                              4: INTERCO_STRENGTH,
                              5: INTERCO_STRENGTH,
                              6: INTERCO_STRENGTH,
                              7: INTERCO_STRENGTH,
                              8: INTERCO_STRENGTH,
                              9: INTERCO_STRENGTH,
                              10: INTERCO_STRENGTH,
                              11: INTERCO_STRENGTH,
                              12: INTERCO_STRENGTH,
                              13: INTERCO_STRENGTH,
                              14: INTERCO_STRENGTH,
                              15: INTERCO_STRENGTH,
                              16: INTERCO_STRENGTH,
                              17: INTERCO_STRENGTH,
                              18: INTERCO_STRENGTH,
                              19: INTERCO_STRENGTH,
                              20: INTERCO_STRENGTH},
                             1: {0: INTERCO_STRENGTH,
                              1: INTERCO_STRENGTH,
                              2: INTERCO_STRENGTH,
                              3: INTERCO_STRENGTH,
                              4: INTERCO_STRENGTH,
                              5: INTERCO_STRENGTH,
                              6: INTERCO_STRENGTH,
                              7: INTERCO_STRENGTH,
                              8: INTERCO_STRENGTH,
                              9: INTERCO_STRENGTH,
                              10: INTERCO_STRENGTH,
                              11: INTERCO_STRENGTH,
                              12: INTERCO_STRENGTH,
                              13: INTERCO_STRENGTH,
                              14: INTERCO_STRENGTH,
                              15: INTERCO_STRENGTH,
                              16: INTERCO_STRENGTH,
                              17: INTERCO_STRENGTH,
                              18: INTERCO_STRENGTH,
                              19: INTERCO_STRENGTH,
                              20: INTERCO_STRENGTH},
                             2: {0: INTERCO_STRENGTH,
                              1: INTERCO_STRENGTH,
                              2: INTERCO_STRENGTH,
                              3: INTERCO_STRENGTH,
                              4: INTERCO_STRENGTH,
                              5: INTERCO_STRENGTH,
                              6: INTERCO_STRENGTH,
                              7: INTERCO_STRENGTH,
                              8: INTERCO_STRENGTH,
                              9: INTERCO_STRENGTH,
                              10: INTERCO_STRENGTH,
                              11: INTERCO_STRENGTH,
                              12: INTERCO_STRENGTH,
                              13: INTERCO_STRENGTH,
                              14: INTERCO_STRENGTH,
                              15: INTERCO_STRENGTH,
                              16: INTERCO_STRENGTH,
                              17: INTERCO_STRENGTH,
                              18: INTERCO_STRENGTH,
                              19: INTERCO_STRENGTH,
                              20: INTERCO_STRENGTH},
                             3: {0: INTERCO_STRENGTH,
                              1: INTERCO_STRENGTH,
                              2: INTERCO_STRENGTH,
                              3: INTERCO_STRENGTH,
                              4: INTERCO_STRENGTH,
                              5: INTERCO_STRENGTH,
                              6: INTERCO_STRENGTH,
                              7: INTERCO_STRENGTH,
                              8: INTERCO_STRENGTH,
                              9: INTERCO_STRENGTH,
                              10: INTERCO_STRENGTH,
                              11: INTERCO_STRENGTH,
                              12: INTERCO_STRENGTH,
                              13: INTERCO_STRENGTH,
                              14: INTERCO_STRENGTH,
                              15: INTERCO_STRENGTH,
                              16: INTERCO_STRENGTH,
                              17: INTERCO_STRENGTH,
                              18: INTERCO_STRENGTH,
                              19: INTERCO_STRENGTH,
                              20: INTERCO_STRENGTH},
                             4: {0: INTERCO_STRENGTH,
                              1: INTERCO_STRENGTH,
                              2: INTERCO_STRENGTH,
                              3: INTERCO_STRENGTH,
                              4: INTERCO_STRENGTH,
                              5: INTERCO_STRENGTH,
                              6: INTERCO_STRENGTH,
                              7: INTERCO_STRENGTH,
                              8: INTERCO_STRENGTH,
                              9: INTERCO_STRENGTH,
                              10: INTERCO_STRENGTH,
                              11: INTERCO_STRENGTH,
                              12: INTERCO_STRENGTH,
                              13: INTERCO_STRENGTH,
                              14: INTERCO_STRENGTH,
                              15: INTERCO_STRENGTH,
                              16: INTERCO_STRENGTH,
                              17: INTERCO_STRENGTH,
                              18: INTERCO_STRENGTH,
                              19: INTERCO_STRENGTH,
                              20: INTERCO_STRENGTH},
                             5: {0: INTERCO_STRENGTH,
                              1: INTERCO_STRENGTH,
                              2: INTERCO_STRENGTH,
                              3: INTERCO_STRENGTH,
                              4: INTERCO_STRENGTH,
                              5: INTERCO_STRENGTH,
                              6: INTERCO_STRENGTH,
                              7: INTERCO_STRENGTH,
                              8: INTERCO_STRENGTH,
                              9: INTERCO_STRENGTH,
                              10: INTERCO_STRENGTH,
                              11: INTERCO_STRENGTH,
                              12: INTERCO_STRENGTH,
                              13: INTERCO_STRENGTH,
                              14: INTERCO_STRENGTH,
                              15: INTERCO_STRENGTH,
                              16: INTERCO_STRENGTH,
                              17: INTERCO_STRENGTH,
                              18: INTERCO_STRENGTH,
                              19: INTERCO_STRENGTH,
                              20: INTERCO_STRENGTH},
                             6: {0: INTERCO_STRENGTH,
                              1: INTERCO_STRENGTH,
                              2: INTERCO_STRENGTH,
                              3: INTERCO_STRENGTH,
                              4: INTERCO_STRENGTH,
                              5: INTERCO_STRENGTH,
                              6: INTERCO_STRENGTH,
                              7: INTERCO_STRENGTH,
                              8: INTERCO_STRENGTH,
                              9: INTERCO_STRENGTH,
                              10: INTERCO_STRENGTH,
                              11: INTERCO_STRENGTH,
                              12: INTERCO_STRENGTH,
                              13: INTERCO_STRENGTH,
                              14: INTERCO_STRENGTH,
                              15: INTERCO_STRENGTH,
                              16: INTERCO_STRENGTH,
                              17: INTERCO_STRENGTH,
                              18: INTERCO_STRENGTH,
                              19: INTERCO_STRENGTH,
                              20: INTERCO_STRENGTH},
                             7: {0: INTERCO_STRENGTH,
                              1: INTERCO_STRENGTH,
                              2: INTERCO_STRENGTH,
                              3: INTERCO_STRENGTH,
                              4: INTERCO_STRENGTH,
                              5: INTERCO_STRENGTH,
                              6: INTERCO_STRENGTH,
                              7: INTERCO_STRENGTH,
                              8: INTERCO_STRENGTH,
                              9: INTERCO_STRENGTH,
                              10: INTERCO_STRENGTH,
                              11: INTERCO_STRENGTH,
                              12: INTERCO_STRENGTH,
                              13: INTERCO_STRENGTH,
                              14: INTERCO_STRENGTH,
                              15: INTERCO_STRENGTH,
                              16: INTERCO_STRENGTH,
                              17: INTERCO_STRENGTH,
                              18: INTERCO_STRENGTH,
                              19: INTERCO_STRENGTH,
                              20: INTERCO_STRENGTH},
                             8: {0: INTERCO_STRENGTH,
                              1: INTERCO_STRENGTH,
                              2: INTERCO_STRENGTH,
                              3: INTERCO_STRENGTH,
                              4: INTERCO_STRENGTH,
                              5: INTERCO_STRENGTH,
                              6: INTERCO_STRENGTH,
                              7: INTERCO_STRENGTH,
                              8: INTERCO_STRENGTH,
                              9: INTERCO_STRENGTH,
                              10: INTERCO_STRENGTH,
                              11: INTERCO_STRENGTH,
                              12: INTERCO_STRENGTH,
                              13: INTERCO_STRENGTH,
                              14: INTERCO_STRENGTH,
                              15: INTERCO_STRENGTH,
                              16: INTERCO_STRENGTH,
                              17: INTERCO_STRENGTH,
                              18: INTERCO_STRENGTH,
                              19: INTERCO_STRENGTH,
                              20: INTERCO_STRENGTH},
                             9: {0: INTERCO_STRENGTH,
                              1: INTERCO_STRENGTH,
                              2: INTERCO_STRENGTH,
                              3: INTERCO_STRENGTH,
                              4: INTERCO_STRENGTH,
                              5: INTERCO_STRENGTH,
                              6: INTERCO_STRENGTH,
                              7: INTERCO_STRENGTH,
                              8: INTERCO_STRENGTH,
                              9: INTERCO_STRENGTH,
                              10: INTERCO_STRENGTH,
                              11: INTERCO_STRENGTH,
                              12: INTERCO_STRENGTH,
                              13: INTERCO_STRENGTH,
                              14: INTERCO_STRENGTH,
                              15: INTERCO_STRENGTH,
                              16: INTERCO_STRENGTH,
                              17: INTERCO_STRENGTH,
                              18: INTERCO_STRENGTH,
                              19: INTERCO_STRENGTH,
                              20: INTERCO_STRENGTH},
                             10: {0: INTERCO_STRENGTH,
                              1: INTERCO_STRENGTH,
                              2: INTERCO_STRENGTH,
                              3: INTERCO_STRENGTH,
                              4: INTERCO_STRENGTH,
                              5: INTERCO_STRENGTH,
                              6: INTERCO_STRENGTH,
                              7: INTERCO_STRENGTH,
                              8: INTERCO_STRENGTH,
                              9: INTERCO_STRENGTH,
                              10: INTERCO_STRENGTH,
                              11: INTERCO_STRENGTH,
                              12: INTERCO_STRENGTH,
                              13: INTERCO_STRENGTH,
                              14: INTERCO_STRENGTH,
                              15: INTERCO_STRENGTH,
                              16: INTERCO_STRENGTH,
                              17: INTERCO_STRENGTH,
                              18: INTERCO_STRENGTH,
                              19: INTERCO_STRENGTH,
                              20: INTERCO_STRENGTH},
                             11: {0: INTERCO_STRENGTH,
                              1: INTERCO_STRENGTH,
                              2: INTERCO_STRENGTH,
                              3: INTERCO_STRENGTH,
                              4: INTERCO_STRENGTH,
                              5: INTERCO_STRENGTH,
                              6: INTERCO_STRENGTH,
                              7: INTERCO_STRENGTH,
                              8: INTERCO_STRENGTH,
                              9: INTERCO_STRENGTH,
                              10: INTERCO_STRENGTH,
                              11: INTERCO_STRENGTH,
                              12: INTERCO_STRENGTH,
                              13: INTERCO_STRENGTH,
                              14: INTERCO_STRENGTH,
                              15: INTERCO_STRENGTH,
                              16: INTERCO_STRENGTH,
                              17: INTERCO_STRENGTH,
                              18: INTERCO_STRENGTH,
                              19: INTERCO_STRENGTH,
                              20: INTERCO_STRENGTH},
                             12: {0: INTERCO_STRENGTH,
                              1: INTERCO_STRENGTH,
                              2: INTERCO_STRENGTH,
                              3: INTERCO_STRENGTH,
                              4: INTERCO_STRENGTH,
                              5: INTERCO_STRENGTH,
                              6: INTERCO_STRENGTH,
                              7: INTERCO_STRENGTH,
                              8: INTERCO_STRENGTH,
                              9: INTERCO_STRENGTH,
                              10: INTERCO_STRENGTH,
                              11: INTERCO_STRENGTH,
                              12: INTERCO_STRENGTH,
                              13: INTERCO_STRENGTH,
                              14: INTERCO_STRENGTH,
                              15: INTERCO_STRENGTH,
                              16: INTERCO_STRENGTH,
                              17: INTERCO_STRENGTH,
                              18: INTERCO_STRENGTH,
                              19: INTERCO_STRENGTH,
                              20: INTERCO_STRENGTH},
                             13: {0: INTERCO_STRENGTH,
                              1: INTERCO_STRENGTH,
                              2: INTERCO_STRENGTH,
                              3: INTERCO_STRENGTH,
                              4: INTERCO_STRENGTH,
                              5: INTERCO_STRENGTH,
                              6: INTERCO_STRENGTH,
                              7: INTERCO_STRENGTH,
                              8: INTERCO_STRENGTH,
                              9: INTERCO_STRENGTH,
                              10: INTERCO_STRENGTH,
                              11: INTERCO_STRENGTH,
                              12: INTERCO_STRENGTH,
                              13: INTERCO_STRENGTH,
                              14: INTERCO_STRENGTH,
                              15: INTERCO_STRENGTH,
                              16: INTERCO_STRENGTH,
                              17: INTERCO_STRENGTH,
                              18: INTERCO_STRENGTH,
                              19: INTERCO_STRENGTH,
                              20: INTERCO_STRENGTH},
                             14: {0: INTERCO_STRENGTH,
                              1: INTERCO_STRENGTH,
                              2: INTERCO_STRENGTH,
                              3: INTERCO_STRENGTH,
                              4: INTERCO_STRENGTH,
                              5: INTERCO_STRENGTH,
                              6: INTERCO_STRENGTH,
                              7: INTERCO_STRENGTH,
                              8: INTERCO_STRENGTH,
                              9: INTERCO_STRENGTH,
                              10: INTERCO_STRENGTH,
                              11: INTERCO_STRENGTH,
                              12: INTERCO_STRENGTH,
                              13: INTERCO_STRENGTH,
                              14: INTERCO_STRENGTH,
                              15: INTERCO_STRENGTH,
                              16: INTERCO_STRENGTH,
                              17: INTERCO_STRENGTH,
                              18: INTERCO_STRENGTH,
                              19: INTERCO_STRENGTH,
                              20: INTERCO_STRENGTH},
                             15: {0: INTERCO_STRENGTH,
                              1: INTERCO_STRENGTH,
                              2: INTERCO_STRENGTH,
                              3: INTERCO_STRENGTH,
                              4: INTERCO_STRENGTH,
                              5: INTERCO_STRENGTH,
                              6: INTERCO_STRENGTH,
                              7: INTERCO_STRENGTH,
                              8: INTERCO_STRENGTH,
                              9: INTERCO_STRENGTH,
                              10: INTERCO_STRENGTH,
                              11: INTERCO_STRENGTH,
                              12: INTERCO_STRENGTH,
                              13: INTERCO_STRENGTH,
                              14: INTERCO_STRENGTH,
                              15: INTERCO_STRENGTH,
                              16: INTERCO_STRENGTH,
                              17: INTERCO_STRENGTH,
                              18: INTERCO_STRENGTH,
                              19: INTERCO_STRENGTH,
                              20: INTERCO_STRENGTH},
                             16: {0: INTERCO_STRENGTH,
                              1: INTERCO_STRENGTH,
                              2: INTERCO_STRENGTH,
                              3: INTERCO_STRENGTH,
                              4: INTERCO_STRENGTH,
                              5: INTERCO_STRENGTH,
                              6: INTERCO_STRENGTH,
                              7: INTERCO_STRENGTH,
                              8: INTERCO_STRENGTH,
                              9: INTERCO_STRENGTH,
                              10: INTERCO_STRENGTH,
                              11: INTERCO_STRENGTH,
                              12: INTERCO_STRENGTH,
                              13: INTERCO_STRENGTH,
                              14: INTERCO_STRENGTH,
                              15: INTERCO_STRENGTH,
                              16: INTERCO_STRENGTH,
                              17: INTERCO_STRENGTH,
                              18: INTERCO_STRENGTH,
                              19: INTERCO_STRENGTH,
                              20: INTERCO_STRENGTH},
                             17: {0: INTERCO_STRENGTH,
                              1: INTERCO_STRENGTH,
                              2: INTERCO_STRENGTH,
                              3: INTERCO_STRENGTH,
                              4: INTERCO_STRENGTH,
                              5: INTERCO_STRENGTH,
                              6: INTERCO_STRENGTH,
                              7: INTERCO_STRENGTH,
                              8: INTERCO_STRENGTH,
                              9: INTERCO_STRENGTH,
                              10: INTERCO_STRENGTH,
                              11: INTERCO_STRENGTH,
                              12: INTERCO_STRENGTH,
                              13: INTERCO_STRENGTH,
                              14: INTERCO_STRENGTH,
                              15: INTERCO_STRENGTH,
                              16: INTERCO_STRENGTH,
                              17: INTERCO_STRENGTH,
                              18: INTERCO_STRENGTH,
                              19: INTERCO_STRENGTH,
                              20: INTERCO_STRENGTH},
                             18: {0: INTERCO_STRENGTH,
                              1: INTERCO_STRENGTH,
                              2: INTERCO_STRENGTH,
                              3: INTERCO_STRENGTH,
                              4: INTERCO_STRENGTH,
                              5: INTERCO_STRENGTH,
                              6: INTERCO_STRENGTH,
                              7: INTERCO_STRENGTH,
                              8: INTERCO_STRENGTH,
                              9: INTERCO_STRENGTH,
                              10: INTERCO_STRENGTH,
                              11: INTERCO_STRENGTH,
                              12: INTERCO_STRENGTH,
                              13: INTERCO_STRENGTH,
                              14: INTERCO_STRENGTH,
                              15: INTERCO_STRENGTH,
                              16: INTERCO_STRENGTH,
                              17: INTERCO_STRENGTH,
                              18: INTERCO_STRENGTH,
                              19: INTERCO_STRENGTH,
                              20: INTERCO_STRENGTH},
                             19: {0: INTERCO_STRENGTH,
                              1: INTERCO_STRENGTH,
                              2: INTERCO_STRENGTH,
                              3: INTERCO_STRENGTH,
                              4: INTERCO_STRENGTH,
                              5: INTERCO_STRENGTH,
                              6: INTERCO_STRENGTH,
                              7: INTERCO_STRENGTH,
                              8: INTERCO_STRENGTH,
                              9: INTERCO_STRENGTH,
                              10: INTERCO_STRENGTH,
                              11: INTERCO_STRENGTH,
                              12: INTERCO_STRENGTH,
                              13: INTERCO_STRENGTH,
                              14: INTERCO_STRENGTH,
                              15: INTERCO_STRENGTH,
                              16: INTERCO_STRENGTH,
                              17: INTERCO_STRENGTH,
                              18: INTERCO_STRENGTH,
                              19: INTERCO_STRENGTH,
                              20: INTERCO_STRENGTH},
                             20: {0: INTERCO_STRENGTH,
                              1: INTERCO_STRENGTH,
                              2: INTERCO_STRENGTH,
                              3: INTERCO_STRENGTH,
                              4: INTERCO_STRENGTH,
                              5: INTERCO_STRENGTH,
                              6: INTERCO_STRENGTH,
                              7: INTERCO_STRENGTH,
                              8: INTERCO_STRENGTH,
                              9: INTERCO_STRENGTH,
                              10: INTERCO_STRENGTH,
                              11: INTERCO_STRENGTH,
                              12: INTERCO_STRENGTH,
                              13: INTERCO_STRENGTH,
                              14: INTERCO_STRENGTH,
                              15: INTERCO_STRENGTH,
                              16: INTERCO_STRENGTH,
                              17: INTERCO_STRENGTH,
                              18: INTERCO_STRENGTH,
                              19: INTERCO_STRENGTH,
                              20: INTERCO_STRENGTH}}
     'homeostasy': True,
     'burnin': 1.  # period of the signal to discard for index computation
    },
'Input':
    {'tau_Ein'  : 3*msecond,
     'g_Ein0'    : 2.*siemens*meter**-2,
     'sigma_Ein' : .035*siemens*meter**-2
    },
'InputOscillation':
    {'f'    : 2*Hz,
     'C'    : 1  # Must be set to 1 for oscillation
    },
'Mitral':
    {'C_m'      : 0.08*farad*meter**-2,
     'g_L'       : 0.87*siemens*meter**-2,
     'E_L'       : -64.5*mvolt,
     'V_r'       : -74*mvolt,
     'V_t'       : -62*mvolt,
     't_refract' : 0.2*msecond
    },
'Granule':
    {'C_m' : 0.01*farad*meter**-2,
     'g_L'  : 0.83*siemens*meter**-2,
     'E_L'  : -70*mvolt,
     'g_SD' : 1*siemens*meter**-2,
     'g_DS' : 300*siemens*meter**-2
    },
'Synapse':
    {'V_E'     : 0*mvolt,
     'V_act_E'  : 0*mvolt,
     'g_E'      : 3.5*siemens*meter**-2/F,
     'sigma_E'  : 0.01*mvolt,
     'alpha_E'  : 10*msecond**-1,
     'beta_E'   : 1./3*msecond**-1,

     'V_I'      : -80*mvolt,
     'V_act_I'  : -66.4*mvolt,
     'g_I'      : 20*siemens*meter**-2,
     'sigma_I'  : 0.4*mvolt,
     'alpha_I'  : 5*msecond**-1,
     'beta_I'   : 1./10*msecond**-1
    },
}
